version: "3.6"

networks:
  global:
    external: true

services:
  coreapp:
    image: registry.gitlab.com/navi-home/coreapp:${CI_APPLICATION_TAG:-latest}
    restart: on-failure:5
    build:
      context: .
      # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference
      args:
        git_tag_ver: ${CI_COMMIT_TAG:-latest}
        git_commit_sha: ${CI_COMMIT_SHORT_SHA:-empty_commit_sha}
        git_branch_name: ${CI_COMMIT_REF_SLUG:-master}
      target: production
    env_file:
      - .env
    environment:
      NODE_ENV: ${APP_ENV:-production}
    ports:
      - 3000:3000/tcp
    networks:
      - global
    command: npm run start:prod

  webapp:
    image: registry.gitlab.com/navi-home/coreapp:${CI_APPLICATION_TAG:-latest}
    restart: on-failure:5
    build:
      context: .
      # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference
      args:
        git_tag_ver: ${CI_COMMIT_TAG:-latest}
        git_commit_sha: ${CI_COMMIT_SHORT_SHA:-empty_commit_sha}
        git_branch_name: ${CI_COMMIT_REF_SLUG:-master}
      target: production
    env_file:
      - .env
    environment:
      NODE_ENV: ${APP_ENV:-production}
    ports:
      - 3000:3000/tcp
    networks:
      - global
    command: npm run start:prod
