version: '3'

services:
  webapp:
    image: registry.gitlab.com/navi-home/webapp:latest
    restart: on-failure:5
    ports:
      - 80:80
    depends_on:
      - coreapp

  coreapp:
    image: registry.gitlab.com/navi-home/coreapp:latest
    restart: on-failure:5
    ports:
      - 3030:3000
    environment:
      NODE_ENV: production
